trigger: none
pr: none

stages:
  - stage:
    displayName: Parallel deployment
    jobs:
      - deployment: AKS
        displayName: Deploy to AKS Environment
        variables:
        - group: chart1-variables-group
        pool:
          vmImage: 'ubuntu-latest'
        environment: AKS.aksnamespace
        strategy:
          runOnce:
            deploy:
              steps:
                - template: deploy-steps-template.yaml
                  parameters:
                    kubernetesCluster: bs-spinnaker
                    rggroup: Spinnaker-k8s
                    env: AKS.aksnamespace
                    namespace: aksnamespace

      - deployment: EKS
        displayName: Deploy to EKS Environment
        variables:
        - group: chart1-variables-group
        pool:
          vmImage: 'ubuntu-latest'
        environment: EKS.eksnamespace
        strategy:
          runOnce:
            deploy:
              steps:
                - template: deploy-steps-template.yaml
                  parameters:
                    kubernetesCluster: bs-spinnaker
                    rggroup: Spinnaker-k8s
                    env: EKS.aksnamespace
                    namespace: eksnamespace

      - deployment: GKE
        displayName: Deploy to GKE Environment
        variables:
        - group: chart1-variables-group
        pool:
          vmImage: 'ubuntu-latest'
        environment: GKE.gkenamespace
        strategy:
          runOnce:
            deploy:
              steps:
                - template: deploy-steps-template.yaml
                  parameters:
                    kubernetesCluster: bs-spinnaker
                    rggroup: Spinnaker-k8s
                    env: GKE.gkenamespace
                    namespace: gkenamespace
