trigger: none
pr: none

variables:
  - template: deploy-common-variables.yaml
    parameters:
      kubernetesCluster: bs-spinnaker
      rggroup: Spinnaker-k8s
      env: AKS.azdevops
      namespace: azdevops

stages:
  - stage:
    displayName: Parallel deployment
    jobs:
      - deployment: AKS
        displayName: Deploy to AKS Environment
        variables:
        - group: chart1-variables-group
        pool:
          vmImage: 'ubuntu-latest'
        environment: AKS.azdevops
        strategy:
          runOnce:
            deploy:
              steps:
                - template: deploy-steps-template.yaml
                  parameters:
                    kubernetesCluster: bs-spinnaker
                    rggroup: Spinnaker-k8s
                    env: AKS.azdevops
                    namespace: azdevops

      - deployment: EKS
        displayName: Deploy to EKS Environment
        variables:
        - group: chart1-variables-group
        pool:
          vmImage: 'ubuntu-latest'
        environment: EKS.aws
        strategy:
          runOnce:
            deploy:
              steps:
                - template: deploy-steps-template.yaml
                  parameters:
                    kubernetesCluster: bs-spinnaker
                    rggroup: Spinnaker-k8s
                    env: EKS.aws
                    namespace: aws

      - deployment: GKE
        displayName: Deploy to GKE Environment
        variables:
        - group: chart1-variables-group
        pool:
          vmImage: 'ubuntu-latest'
        environment: GKE.google
        strategy:
          runOnce:
            deploy:
              steps:
                - template: deploy-steps-template.yaml
                  parameters:
                    kubernetesCluster: bs-spinnaker
                    rggroup: Spinnaker-k8s
                    env: GKE.google
                    namespace: google
