trigger: none
pr: none

stages:
  - stage:
    displayName: Deploy to AKS

	jobs:
	- deployment:
	  displayName: Deploy to AKS
	  pool:
		vmImage: ubuntu-latest
	  environment: AKS.aksnamespace
	  strategy:
		runOnce:
		  deploy:
			  steps:
				- template: deploy-steps-template.yaml
				  parameters:
					kubernetesCluster: bs-spinnaker
					rggroup: Spinnaker-k8s
					env: AKS.aksnamespace
					namespace: aksnamespace
	- deployment:
	  displayName: Deploy to GKE
	  pool:
		vmImage: ubuntu-latest
	  environment: GKE.gkenamespace
	  strategy:
		runOnce:
		  deploy:
			  steps:
				- template: deploy-steps-template.yaml
				  parameters:
					kubernetesCluster: bs-spinnaker
					rggroup: Spinnaker-k8s
					env: GKE.gkenamespace
					namespace: gkenamespace
	- deployment:
	  displayName: Deploy to EKS
	  pool:
		vmImage: ubuntu-latest
	  environment: EKS.eksnamespace
	  strategy:
		runOnce:
		  deploy:
			  steps:
				- template: deploy-steps-template.yaml
				  parameters:
					kubernetesCluster: bs-spinnaker
					rggroup: Spinnaker-k8s
					env: EKS.eksnamespace
					namespace: eksnamespace
