trigger:
  batch: true
  paths:
    include:
      - testkubernetes/azure-pipelines.deploy.yaml
  branches:
    include:
      - main

variables:
  - template: deploy-variable-template.yaml
    parameters:
      kubernetesCluster: bs-spinnaker
      rggroup: Spinnaker-k8s
      env: QA.azdevops
      namespace: azdevops

stages:
  - stage:
    displayName: Deploy to QA
    jobs:
      - deployment: QA
        displayName: Deploy to QA Environment
        pool:
          vmImage: 'ubuntu-latest'
        environment: '$(env)'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: HelmInstaller@1
                  displayName: 'Install Helm'
                  inputs:
                    helmVersionToInstall: '$(helmVersion)'

                - task: AzureCLI@2
                  displayName: 'Add ACR to Helm Repository list'
                  inputs:
                    azureSubscription: '$(azuresubscription)'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: 'az acr helm repo add --name $(containerRegistry)'
                    failOnStandardError: false
                    
                - task: HelmDeploy@0
                  displayName: 'Helm Deploy'
                  inputs:
                    connectionType: 'Azure Resource Manager'
                    azureSubscription: '$(azuresubscription)'
                    azureResourceGroup: '$(rggroup)'
                    kubernetesCluster: '$(kubernetesCluster)'
                    azureContainerRegistry: '$(containerRegistry)'
                    azureResourceGroupForACR: '$(rggroup)'
                    azureSubscriptionForACR: '$(azuresubscription)'
                    useClusterAdmin: true
                    namespace: '$(namespace)'
                    command: upgrade
                    chartType: Name
                    chartPath: spinkube-chart
                    chartName: spinkube-chart
                    releaseName: spinkube-chart
                    install: true
                    #overrideValues: 'image.repository=$(containerRegistry).azurecr.io/$(containerRepository)'
